version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "triangle_app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234567"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
      build: .
      volumes:
        - .:/opt/app
      ports:
        - "8000:8000"
      depends_on:
        - postgres
volumes:
  habrdb-data:
